/*
    username: ammdb
    password: ammdb
 */


create table utente(
    id_utente integer generated by default as identity primary key,
    nome varchar(32),
    cognome varchar(32),
    dataNascita date,
    biografia varchar(140),
    password varchar(16) not null,
    urlFotoProfilo varchar(256),
    superUtente boolean not null,
    email varchar(64) not null unique
    
);

create table postType(
    id_postType integer generated by default as identity primary key,
    nome varchar(16) unique
);

create table gruppo(
    id_gruppo integer generated by default as identity primary key,
    nome varchar(256),
    admin integer references utente on delete cascade
);

create table post(
    id_post integer generated by default as identity primary key,
    content varchar(2048),
    urlAllegato varchar(256),
    tipo integer references postType on delete cascade not null,
    autore integer references utente on delete cascade,
    utenteDestinatario integer references utente on delete cascade,
    gruppoDestinatario integer references gruppo on delete cascade,
    check ((utenteDestinatario is null and gruppoDestinatario is not null)
            or (gruppoDestinatario is null and utenteDestinatario is not null))
);

create table amicizia(
    utente integer references utente on delete cascade,
    amico integer references utente on delete cascade,
    primary key (utente, amico)
);

create table appartenenzaGruppo(
    utente integer references utente on delete cascade,
    gruppo integer references gruppo on delete cascade,
    primary key (utente, gruppo)
);



insert into utente(id_utente,email , nome, cognome, dataNascita, biografia, password, urlFotoProfilo, superUtente)
values  (default, 'black@gmail.com','Black', 'Seppia', '1956-09-27', 'Dipingo', '111', '../img/BlackSeppia.jpg', true),
    (default, 'gigi@gmail.com', 'Gigi', 'Proiettile', '1980-10-15', null, '111', '../img/GigiProiettile.jpg', false),
        (default, 'pinina@gmail.com', 'Pinina', 'Caravaglia', '1932-12-03', 'Mi è sembrato di vedere un gatto!', '111', '../img/Pinina.jpg', false),
        (default, 'nerdina@gmail.com', 'Nerd', 'Nina', '1992-06-11', null, '111', '../img/NerdNina.jpg', false
         default, 'eliminami@gmai.com', 'El', 'Iminato','1999-01-01', null, '111', '../img/eliminato.jpg');     

insert into postType(id_postType, nome)
values  (default, 'text'), 
    (default, 'image'), 
    (default, 'link'); 
        
insert into gruppo(id_gruppo, nome, admin)
values  (default, 'Gruppo2', 1),
    (default, 'Gruppo1', 4),
        (default, 'Eliminare', 5);
        
insert into post(id_post, autore, utenteDestinatario, gruppoDestinatario, tipo, content, urlAllegato)
values  (default, 1, 1, null, 1, 'Come va?', ''),
        (default, 1, 2, null, 2, '', 'img/Ok.jpg'),
        (default, 2, 1, null, 2, 'Check out this manzo', 'img/PaoloBrosio.jpeg'),
        (default, 3, 3, null, 2, '', 'img/111.jpg'),
        (default, 2, 2, null, 1, 'Ciao e buona giornata a tutti amici', ''),
        (default, 4, 4, null, 3, 'Mario!!!', 'https://www.youtube.com/watch?v=5qgOeXbFQ9U'),
        (default, 1, null, 2, 1, 'Quanto sale si mette per fare il pane?', ''),
        (default, 5, null, 3, 1, 'aaaaaaaaaaaaaa ','');
        
insert into amicizia(utente, amico)
values  (1, 2),
        (1, 3),
        (1, 4),
        (2, 1),
        (2, 4),
        (3, 1),
        (3, 4),
        (4, 1),
        (4, 2),
        (4, 3),
        (5, 1),
        (1, 5);
       
        
insert into appartenenzaGruppo( utente, gruppo)
values  (1, 1),
        (2, 1),
        (3, 1),
        (4, 1),
        (1, 2),
        (3, 2),
        (4, 2),
        (5, 3),
        (1, 3);
        
